jobs:
  build:
    docker:
      - image: flyingp0tat0:cordova-android

    steps:
      - run: cordova create test
      - run: cd test && cordova platform add android
      - run: cd test && cordova plugin add https://github.com/fbsanches/cordova-plugin-wallpaper
      - run: cd test && cordova build
